[package]
name = "volsnap-runner"
version = "1.0.0"
edition = "2024"

[dependencies]
anyhow = "1.0.97"
clap = "4.5.31"
fs_extra = "1.3.0"
serde_json = "1.0.140"
tar = "0.4.44"
volsnap-library = { path = "../library" }
zstd = "0.13.3"
