[package]
name = "vsnap-cli"
version = "1.0.0"
edition = "2024"

[dependencies]
anyhow = "1.0.97"
bollard = "0.18.1"
chrono = "0.4.40"
clap = { version = "4.5.31", features = ["derive"] }
serde = { version = "1.0.219", features = ["derive"] }
tokio = { version = "1.44.0", features = ["rt-multi-thread", "macros"] }
